#!/bin/bash
set -x
SCRIPTBASE=$(readlink -nf $(dirname $0))
source "$SCRIPTBASE/functions.sh"

case "$(node_status)" in
    RUNNING|STARTING)
        exit 0
        ;;
esac

for opt in $@ ; do
    case "$opt" in
        clean)
            rm -fr $NODE_BASE/over || true
            ;;
    esac
done

run() {
    node_provision
    mount_fs
    node_start && exit 0

    echo "$NODE_ID: Start TIMEOUT"
    node_stop
    umount_fs
    exit 1
}

mkdir -p $NODE_BASE
run 2>&1 | tee $NODE_BASE/start.log 1>&2
