#!/bin/bash
set -x
SCRIPTBASE=$(readlink -nf $(dirname $0))
source "$SCRIPTBASE/functions.sh"

node_stop
umount_fs

for opt in $@ ; do
    case "$opt" in
        clean)
            rm -fr $NODE_BASE || true
            ;;
    esac
done
