#!/bin/bash

ID=$1
NAME=${CLUSTER_NAME}-$ID
BASE=$CLUSTER_BASE/nodes/node-$ID

STATUS=$(lxc-info -n $NAME 2>/dev/null | grep 'state:' | sed -r 's/^state:[[:space:]]*([^[:space:]]+).*$/\1/')

case "$STATUS" in
    RUNNING|STARTING|FREEZING|FROZEN)
        lxc-stop -n $NAME
        ;;
esac

for dir in root os base ; do
    ! mountpoint $BASE/$dir || umount $BASE/$dir
done
